### ISSUE TITLE
I am getting Cannot set properties of undefined (setting 'workerSrc')

### ISSUE THREAD

**Issue by shilpa5010** [gspasov/svelte-pdf-simple#8]
I have installed and trying to use in my application but I see its undefined, can someone help on this why i am getting this issue
in nodes_module/svelte-pdf-simple/pdfViewer.svelte if I make this change like 

Replace import * as pdfjs from "pdfjs-dist"; with import pdfjs from "pdfjs-dist"; it is working fine, not sure whats wrong with it.
Can you please help on this.
```
Stack Trace
TypeError: Cannot set properties of undefined (setting 'workerSrc')
    at /Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/node_modules/svelte-pdf-simple/pdfViewer.svelte:42:36
    at Object.$$render (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.default (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/src/components/fragments/flipbook/pdf.svelte:59:51)
    at eval (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/node_modules/svelte-fullscreen/dist/Fullscreen.svelte:49:17)
    at Object.$$render (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at eval (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/src/components/fragments/flipbook/pdf.svelte:74:105)
    at $$render (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.render (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/node_modules/svelte/src/runtime/internal/ssr.js:164:17)
    at Object.renderToStaticMarkup (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/node_modules/@astrojs/svelte/server.js:17:29)
    at renderFrameworkComponent (/Users/shilpag/Docker/work/newproject/new_services/main_07_06/groundhog-frontend/frontend/node_modules/astro/dist/runtime/server/render/component.js:197:66)
```

**Comment by bluepuma77** [comment]
Similar error for me.
```
<script lang="ts">
	import { PdfViewer } from 'svelte-pdf-simple';
	const urlToPdf =
		'https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf';
</script>

<PdfViewer url={urlToPdf} />
```

```
TypeError: Cannot set properties of undefined (setting 'workerSrc')
    at /xyz/app/node_modules/svelte-pdf-simple/pdfViewer.svelte:42:36
```

**Comment by purohitdheeraj** [comment]
@bluepuma77 @shilpa5010 

i tried dynamic import it worked for me

```<script lang="ts">
	let PdfViewer;
	export let resumeUrl =
		'https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/examples/learning/helloworld.pdf';

	// Lazy load the PdfViewer component
	async function loadPdfViewer() {
		const module = await import('svelte-pdf-simple');
		PdfViewer = module.PdfViewer;
	}

	// Automatically load the component when the script runs
	loadPdfViewer();
</script>

<main>
	{#if PdfViewer}
		<PdfViewer
			props={{
				path: resumeUrl,
				scale: 1.5,
				withAnnotations: true,
				withTextContent: true
			}}
			style="border:1px solid;display: block; margin-top: 10px; width:100%"
		/>
	{:else}
		<p>Loading PDF Viewer...</p>
	{/if}
</main>
```

**Comment by sanjusoftware** [comment]
exactly same issue for me as well and workaround suggested by @purohitdheeraj worked!!

I am wondering though @gspasov , if this is how it is supposed to be?? if yes, perhaps the documentation should be updated. If not, I am wondering what's wrong. Any chance you looked into this already?
